name: Generate RSS Feed

on:
  push:
    branches: [ main ]
    paths:
      - '_posts/**'
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        # 移除缓存配置，避免需要 package-lock.json

    - name: Install dependencies
      run: npm install marked gray-matter

    - name: Generate RSS Feed
      run: node generate-rss.js

    - name: Commit and push RSS feed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add rss.xml
        git diff --quiet && git diff --staged --quiet || git commit -m "Update RSS feed"
        git push
